// Note: having length != 4 will mess with layout based on how the site is styled
const bookmarks = [
  {
    title: "social.",
    links: [
      { name: "Reddit.", url: "https://www.reddit.com" },
      { name: "Lemmy.", url: "https://lemmy.ml/" },
      { name: "Facebook.", url: "https://www.facebook.com" },
      { name: "Telegram.", url: "https://web.telegram.org/k/" },
      { name: "Twitter.", url: "https://www.twitter.com" },
      { name: "Tumblr.", url: "https://www.tumblr.com" },
      { name: "Discord.", url: "https://discord.com/channels/@me" },
      { name: "Revolt.", url: "https://app.revolt.chat/" },
      { name: "Spacehey.", url: "https://www.spacehey.com" },
    ],
  },
  {
    title: "general.",
    links: [
      { name: "GitHub.", url: "https://github.com/sbfse?tab=stars" },
      { name: "Archive.", url: "https://archive.org/details/fav-subfuse" },
      { name: "PICO-8.", url: "https://www.lexaloffle.com/pico-8.php" },
      { name: "TIC80.", url: "https://tic80.com/" },
      { name: "WIN93.", url: "http://www.windows93.net/" },
      { name: "SimpleMMO.", url: "https://web.simple-mmo.com/" },
      { name: "4chan.", url: "https://www.4chan.org" },
      { name: "XDA.", url: "https://forum.xda-developers.com/" },
      { name: "dA.", url: "https://www.deviantart.com" },
      { name: "RetroA.", url: "https://retroachievements.org/user/subfuse" },
      { name: "Exophase.", url: "https://www.exophase.com/user/subfuse/" },
      { name: "s-ul.", url: "https://s-ul.eu/files" },
      { name: "Snapdrop.", url: "https://snapdrop.net/" },
      { name: "GetC.", url: "https://getcomics.info/" },
      { name: "Useless.", url: "https://www.theuselesswebindex.com/" },
      { name: "StmbldTo.", url: "https://stumbled.to/stumble" },
      { name: "Stmblng.", url: "https://stumblingon.com/" },
      { name: "Readspike.", url: "https://spike.news/login" },
      { name: "/r/andom.", url: "https://www.reddit.com/r/random/" },
    ],
  },
  {
    title: "video.",
    links: [
      { name: "Youtube.", url: "https://youtube.com" },
      { name: "Twitch.", url: "https://twitch.tv" },
      { name: "WCOfun.", url: "https://www.wcofun.net/" },
      { name: "Toonami.", url: "https://www.toonamiaftermath.com/" },
      { name: "Trakt.", url: "https://trakt.tv/users/subfuse" },
    ],
  },
  {
    title: "music.",
    links: [
      { name: "YTMusic.", url: "https://music.youtube.com/" },
      { name: "Spotify.", url: "https://open.spotify.com/" },
      { name: "Deezer.", url: "https://www.deezer.com/us/profile/1972525046/playlists" },
      { name: "TT.fm.", url: "https://turntable.fm" },
      { name: "Radio.G.", url: "http://radio.garden" },
      { name: "Plaza.", url: "http://plaza.one" },
      { name: "Lofi.", url: "https://lofi.cafe" },
      { name: "Pool.", url: "https://poolsuite.net/" },
      { name: "chip.", url: "https://chiptune.app/browse" },
      { name: "NR.fm.", url: "https://nightride.fm/" },
      { name: "Last.FM.", url: "https://www.last.fm/user/sbfse" },
    ],
  },
  {
    title: "coding.",
    links: [
      { name: "Freecode.", url: "https://www.freecodecamp.org/learn" },
      { name: "CodeCDMY.", url: "https://www.codecademy.com/profiles/sbfse" },
      { name: "Exercism.", url: "https://exercism.org/dashboard" },
      { name: "CodinG.", url: "https://www.codingame.com/start/" },
      { name: "edX.", url: "https://courses.edx.org/dashboard" },
      { name: "Vercel.", url: "https://vercel.com/dashboard" },
      { name: "Code.org.", url: "https://studio.code.org/home" },
      { name: "w3school.", url: "https://my-learning.w3schools.com/" },
      { name: "Coursera.", url: "https://www.coursera.org/search?query=solidity&" },
      { name: "Stack.", url: "https://stackoverflow.com/" },
      { name: "nextJS.", url: "https://nextjs.org/learn-pages-router/basics/create-nextjs-app" },
      { name: "Hacksplain.", url: "https://www.hacksplaining.com/lessons" },
    ],
  },
  {
    title: "piracy.",
    links: [
      { name: "/r/FMHY.", url: "https://fmhy.pages.dev/" },
      { name: "pgames.", url: "https://rentry.org/pgames" },
      { name: "mega.", url: "https://rentry.co/megathread" },
      { name: "Champagne.", url: "https://champagne.pages.dev/" },
      { name: "Ripped.", url: "https://ripped.guide/" },
      { name: "SteamRIP.", url: "https://steamrip.com/" },
      { name: "GOGgames.", url: "https://www.gog-games.to/" },
      { name: "1337x.to.", url: "https://1337x.to/" },
      { name: "BTDig.", url: "https://btdig.com/index.htm" },
      { name: "ROMs.", url: "https://crocdb.net/" },
      { name: "libgen.", url: "http://libgen.is/" },
      { name: "Mobilism.", url: "https://forum.mobilism.org/viewforum.php?f=399" },
    ],
  },
  {
    title: "html.",
    links: [
      { name: "Bearblog.", url: "https://bearblog.dev/dashboard/" },
      { name: "Geocities.", url: "https://members.geocities.ws/fm/index.php" },
      { name: "Neocities.", url: "https://neocities.org/dashboard" },
      { name: "Carrd.", url: "https://carrd.co/" },
    ],
  },
  {
    title: "emails.",
    links: [
      { name: "Gmail.", url: "https://www.gmail.com" },
      { name: "Live.", url: "https://www.live.com" },
      { name: "Proton.", url: "https://mail.protonmail.com/u/0/inbox" },
      { name: "Fake.", url: "https://www.fakemailgenerator.com" },
    ],
  },
];
